### ISSUE TITLE
Update to latest version

### ISSUE THREAD

**Issue by Moulick** [whatpulse/homebrew-whatpulse#1]
The Version on the website is 5.7, this tap currently offers an older version. Please update the tap to reflect the latest version

**Comment by smitmartijn** [comment]
@Moulick it might be old, but the first thing WhatPulse will do is update to the latest version, so it really doesn't matter which version the brew has.

**Comment by Moulick** [comment]
That might be true but brew being a package manager, the goal is not to upgrade an application outside brew. In most cases people disable auto update in applications if installed via brew. Having the application autoupdate sort of defeats the purpose of homebrew. So either this tap should not exist and the only way to upgrade should be the in-built auto upgrade or this tap should also be kept upto date with the latest release in the website.

Opening a PR to keep this updated is also very easy, only need to run `brew bump --open-pr <cask-name>` and brew will create the PR based on the version it finds from the livecheck stanza.
